import { ConfigDefinition } from './types';

/**
 * Agent behavior configuration definitions
 *
 * Controls AI agent parameters like temperature, confidence thresholds,
 * and timeouts.
 */
export const AGENT_CONFIG_DEFINITIONS: ConfigDefinition[] = [
  // === Temperature Settings ===
  {
    domain: 'agent',
    key: 'chat_temperature',
    valueType: 'number',
    description: 'Temperature for chat agent responses (0.0 = deterministic, 1.0 = creative)',
    envVarName: 'AGENT_CHAT_TEMPERATURE',
    codeDefault: 0.7,
    validation: { min: 0, max: 1 },
    category: 'temperature',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'atomization_temperature',
    valueType: 'number',
    description: 'Temperature for atomization analysis (lower = more consistent)',
    envVarName: 'AGENT_ATOMIZATION_TEMPERATURE',
    codeDefault: 0.2,
    validation: { min: 0, max: 1 },
    category: 'temperature',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'commitment_temperature',
    valueType: 'number',
    description: 'Temperature for commitment agent proposals',
    envVarName: 'AGENT_COMMITMENT_TEMPERATURE',
    codeDefault: 0.3,
    validation: { min: 0, max: 1 },
    category: 'temperature',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'refinement_temperature',
    valueType: 'number',
    description: 'Temperature for intent refinement agent',
    envVarName: 'AGENT_REFINEMENT_TEMPERATURE',
    codeDefault: 0.3,
    validation: { min: 0, max: 1 },
    category: 'temperature',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'atomicity_checker_temperature',
    valueType: 'number',
    description: 'Temperature for atomicity checker (lower = more consistent)',
    envVarName: 'AGENT_ATOMICITY_CHECKER_TEMPERATURE',
    codeDefault: 0.2,
    validation: { min: 0, max: 1 },
    category: 'temperature',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'brownfield_temperature',
    valueType: 'number',
    description: 'Temperature for brownfield analysis agent',
    envVarName: 'AGENT_BROWNFIELD_TEMPERATURE',
    codeDefault: 0.2,
    validation: { min: 0, max: 1 },
    category: 'temperature',
    requiresRestart: false,
  },

  // === Confidence Thresholds ===
  {
    domain: 'agent',
    key: 'confidence_threshold_atomicity',
    valueType: 'number',
    description: 'Minimum confidence score for atomicity analysis to be accepted',
    envVarName: 'LLM_CONFIDENCE_THRESHOLD_ATOMICITY',
    codeDefault: 0.7,
    validation: { min: 0.5, max: 1 },
    category: 'quality',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'confidence_threshold_testability',
    valueType: 'number',
    description: 'Minimum confidence score for testability analysis',
    envVarName: 'LLM_CONFIDENCE_THRESHOLD_TESTABILITY',
    codeDefault: 0.7,
    validation: { min: 0.5, max: 1 },
    category: 'quality',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'confidence_threshold_translation',
    valueType: 'number',
    description: 'Minimum confidence score for validator translation',
    envVarName: 'LLM_CONFIDENCE_THRESHOLD_TRANSLATION',
    codeDefault: 0.6,
    validation: { min: 0.5, max: 1 },
    category: 'quality',
    requiresRestart: false,
  },

  // === Timeouts ===
  {
    domain: 'agent',
    key: 'default_timeout',
    valueType: 'number',
    description: 'Default timeout for LLM requests in milliseconds',
    envVarName: 'LLM_DEFAULT_TIMEOUT',
    codeDefault: 120000,
    validation: { min: 10000, max: 300000 },
    category: 'timeout',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'synthesize_timeout',
    valueType: 'number',
    description: 'Timeout for synthesis operations in milliseconds',
    envVarName: 'AGENT_SYNTHESIZE_TIMEOUT',
    codeDefault: 90000,
    validation: { min: 30000, max: 180000 },
    category: 'timeout',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'max_iterations',
    valueType: 'number',
    description: 'Maximum graph iterations for agent exploration',
    envVarName: 'AGENT_MAX_ITERATIONS',
    codeDefault: 5,
    validation: { min: 1, max: 20 },
    category: 'limits',
    requiresRestart: false,
  },

  // === Token Limits ===
  {
    domain: 'agent',
    key: 'max_tokens',
    valueType: 'number',
    description: 'Maximum tokens for LLM output',
    envVarName: 'LLM_MAX_TOKENS',
    codeDefault: 4096,
    validation: { min: 256, max: 32000 },
    category: 'limits',
    requiresRestart: false,
  },
  {
    domain: 'agent',
    key: 'max_context_chars',
    valueType: 'number',
    description: 'Maximum context characters before truncation',
    envVarName: 'AGENT_MAX_CONTEXT_CHARS',
    codeDefault: 100000,
    validation: { min: 10000, max: 500000 },
    category: 'limits',
    requiresRestart: false,
  },
];
