import { ConfigDefinition } from './types';

/**
 * Resilience configuration definitions
 *
 * Controls circuit breaker, retry policies, and rate limiting.
 */
export const RESILIENCE_CONFIG_DEFINITIONS: ConfigDefinition[] = [
  // === Circuit Breaker ===
  {
    domain: 'resilience',
    key: 'circuit_breaker_enabled',
    valueType: 'boolean',
    description: 'Enable circuit breaker for LLM provider failures',
    envVarName: 'CIRCUIT_BREAKER_ENABLED',
    codeDefault: true,
    category: 'circuit_breaker',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'circuit_breaker_failure_threshold',
    valueType: 'number',
    description: 'Number of failures before opening the circuit',
    envVarName: 'CIRCUIT_BREAKER_FAILURE_THRESHOLD',
    codeDefault: 5,
    validation: { min: 1, max: 20 },
    category: 'circuit_breaker',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'circuit_breaker_success_threshold',
    valueType: 'number',
    description: 'Number of successes before closing the circuit',
    envVarName: 'CIRCUIT_BREAKER_SUCCESS_THRESHOLD',
    codeDefault: 2,
    validation: { min: 1, max: 10 },
    category: 'circuit_breaker',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'circuit_breaker_timeout',
    valueType: 'number',
    description: 'Time in ms before attempting to close circuit',
    envVarName: 'CIRCUIT_BREAKER_TIMEOUT',
    codeDefault: 60000,
    validation: { min: 5000, max: 300000 },
    category: 'circuit_breaker',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'circuit_breaker_monitoring_window',
    valueType: 'number',
    description: 'Window in ms for tracking failures',
    envVarName: 'CIRCUIT_BREAKER_MONITORING_WINDOW',
    codeDefault: 120000,
    validation: { min: 30000, max: 600000 },
    category: 'circuit_breaker',
    requiresRestart: false,
  },

  // === Retry Policy ===
  {
    domain: 'resilience',
    key: 'retry_enabled',
    valueType: 'boolean',
    description: 'Enable automatic retries for failed requests',
    envVarName: 'RETRY_ENABLED',
    codeDefault: true,
    category: 'retry',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'retry_max_retries',
    valueType: 'number',
    description: 'Maximum number of retry attempts',
    envVarName: 'RETRY_MAX_RETRIES',
    codeDefault: 3,
    validation: { min: 0, max: 10 },
    category: 'retry',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'retry_initial_delay',
    valueType: 'number',
    description: 'Initial delay between retries in ms',
    envVarName: 'RETRY_INITIAL_DELAY',
    codeDefault: 1000,
    validation: { min: 100, max: 10000 },
    category: 'retry',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'retry_max_delay',
    valueType: 'number',
    description: 'Maximum delay between retries in ms',
    envVarName: 'RETRY_MAX_DELAY',
    codeDefault: 10000,
    validation: { min: 1000, max: 60000 },
    category: 'retry',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'retry_backoff_multiplier',
    valueType: 'number',
    description: 'Multiplier for exponential backoff',
    envVarName: 'RETRY_BACKOFF_MULTIPLIER',
    codeDefault: 2,
    validation: { min: 1, max: 5 },
    category: 'retry',
    requiresRestart: false,
  },

  // === Rate Limiting ===
  {
    domain: 'resilience',
    key: 'rate_limit_enabled',
    valueType: 'boolean',
    description: 'Enable rate limiting for LLM requests',
    envVarName: 'RATE_LIMIT_ENABLED',
    codeDefault: true,
    category: 'rate_limit',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'rate_limit_requests_per_minute',
    valueType: 'number',
    description: 'Maximum requests per minute',
    envVarName: 'RATE_LIMIT_REQUESTS_PER_MINUTE',
    codeDefault: 60,
    validation: { min: 10, max: 1000 },
    category: 'rate_limit',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'rate_limit_burst_size',
    valueType: 'number',
    description: 'Burst size for rate limiting',
    envVarName: 'RATE_LIMIT_BURST_SIZE',
    codeDefault: 10,
    validation: { min: 1, max: 100 },
    category: 'rate_limit',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'rate_limit_queue_enabled',
    valueType: 'boolean',
    description: 'Enable request queuing when rate limited',
    envVarName: 'RATE_LIMIT_QUEUE_ENABLED',
    codeDefault: true,
    category: 'rate_limit',
    requiresRestart: false,
  },
  {
    domain: 'resilience',
    key: 'rate_limit_max_queue_size',
    valueType: 'number',
    description: 'Maximum queue size for rate limited requests',
    envVarName: 'RATE_LIMIT_MAX_QUEUE_SIZE',
    codeDefault: 100,
    validation: { min: 10, max: 1000 },
    category: 'rate_limit',
    requiresRestart: false,
  },
];
