import { ConfigDefinition } from './types';

/**
 * Safety configuration definitions
 *
 * Controls security thresholds and behavior.
 * Most settings are view-only for security reasons.
 */
export const SAFETY_CONFIG_DEFINITIONS: ConfigDefinition[] = [
  // === Adjustable Thresholds ===
  {
    domain: 'safety',
    key: 'block_threshold',
    valueType: 'number',
    description: 'Risk score threshold above which requests are blocked (0-100)',
    envVarName: 'SAFETY_BLOCK_THRESHOLD',
    codeDefault: 80,
    validation: { min: 50, max: 100 },
    category: 'thresholds',
    requiresRestart: false,
    isEditable: true,
  },
  {
    domain: 'safety',
    key: 'log_violations',
    valueType: 'boolean',
    description: 'Log all safety violations for auditing',
    envVarName: 'SAFETY_LOG_VIOLATIONS',
    codeDefault: true,
    category: 'logging',
    requiresRestart: false,
    isEditable: true,
  },
  {
    domain: 'safety',
    key: 'block_on_critical',
    valueType: 'boolean',
    description: 'Immediately block requests with critical violations',
    envVarName: 'SAFETY_BLOCK_ON_CRITICAL',
    codeDefault: true,
    category: 'behavior',
    requiresRestart: false,
    isEditable: true,
  },

  // === Hard Limits (View-Only) ===
  {
    domain: 'safety',
    key: 'max_input_length',
    valueType: 'number',
    description: 'Maximum input length in characters',
    codeDefault: 50000,
    category: 'limits',
    requiresRestart: true,
    isEditable: false,
  },
  {
    domain: 'safety',
    key: 'max_output_length',
    valueType: 'number',
    description: 'Maximum output length in characters',
    codeDefault: 100000,
    category: 'limits',
    requiresRestart: true,
    isEditable: false,
  },
  {
    domain: 'safety',
    key: 'max_tool_calls_per_request',
    valueType: 'number',
    description: 'Maximum tool calls allowed per request',
    codeDefault: 20,
    category: 'limits',
    requiresRestart: true,
    isEditable: false,
  },
  {
    domain: 'safety',
    key: 'max_tool_execution_time',
    valueType: 'number',
    description: 'Maximum tool execution time in milliseconds',
    codeDefault: 30000,
    category: 'limits',
    requiresRestart: true,
    isEditable: false,
  },
  {
    domain: 'safety',
    key: 'max_file_read_size',
    valueType: 'number',
    description: 'Maximum file read size in bytes',
    codeDefault: 1000000,
    category: 'limits',
    requiresRestart: true,
    isEditable: false,
  },
  {
    domain: 'safety',
    key: 'max_directory_depth',
    valueType: 'number',
    description: 'Maximum directory traversal depth',
    codeDefault: 10,
    category: 'limits',
    requiresRestart: true,
    isEditable: false,
  },

  // === Detection Settings (View-Only) ===
  {
    domain: 'safety',
    key: 'sanitize_input',
    valueType: 'boolean',
    description: 'Sanitize all input before processing',
    codeDefault: true,
    category: 'detection',
    requiresRestart: true,
    isEditable: false,
  },
  {
    domain: 'safety',
    key: 'validate_output',
    valueType: 'boolean',
    description: 'Validate all output before returning',
    codeDefault: true,
    category: 'detection',
    requiresRestart: true,
    isEditable: false,
  },
  {
    domain: 'safety',
    key: 'detect_injection',
    valueType: 'boolean',
    description: 'Detect prompt injection attempts',
    codeDefault: true,
    category: 'detection',
    requiresRestart: true,
    isEditable: false,
  },
  {
    domain: 'safety',
    key: 'block_sensitive_files',
    valueType: 'boolean',
    description: 'Block access to sensitive files (.env, credentials, etc.)',
    codeDefault: true,
    category: 'detection',
    requiresRestart: true,
    isEditable: false,
  },
];
