import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  OneToMany,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import type { AtomRecommendation } from './atom-recommendation.entity';
import type { MoleculeRecommendation } from './molecule-recommendation.entity';
import type { TestRecord } from './test-record.entity';
import type { Project } from '../../projects/project.entity';

/**
 * Reconciliation mode: full-scan or delta
 */
export type ReconciliationMode = 'full-scan' | 'delta';

/**
 * Status of a reconciliation run
 */
export type ReconciliationRunStatus = 'running' | 'completed' | 'failed' | 'pending_review';

/**
 * Summary of reconciliation results
 */
export interface ReconciliationSummary {
  totalOrphanTests: number;
  inferredAtomsCount: number;
  inferredMoleculesCount: number;
  qualityPassCount: number;
  qualityFailCount: number;
  changedAtomLinkedTestCount?: number;
  duration?: number;
  llmCalls?: number;
}

/**
 * Options used for the reconciliation run
 */
export interface ReconciliationRunOptions {
  analyzeDocs?: boolean;
  maxTests?: number;
  autoCreateAtoms?: boolean;
  qualityThreshold?: number;
  requireReview?: boolean;
  [key: string]: unknown;
}

/**
 * ReconciliationRun entity tracks each execution of the reconciliation agent.
 *
 * This entity stores:
 * - Run configuration and status
 * - Delta baseline information (for incremental runs)
 * - Summary statistics
 * - The reconciliation patch (operations to apply)
 *
 * @see docs/implementation-checklist-phase5.md Section 3.5
 */
@Entity('reconciliation_runs')
export class ReconciliationRun {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * Human-readable run ID (e.g., "REC-001")
   */
  @Column({ unique: true, length: 20 })
  runId: string;

  /**
   * Root directory that was analyzed
   */
  @Column('text')
  rootDirectory: string;

  /**
   * Mode: full-scan or delta
   */
  @Column({ length: 20 })
  reconciliationMode: ReconciliationMode;

  /**
   * For delta mode: reference to the baseline run
   */
  @Column({ type: 'uuid', nullable: true })
  deltaBaselineRunId: string | null;

  /**
   * For delta mode: git commit hash of the baseline
   */
  @Column({ type: 'varchar', length: 64, nullable: true })
  deltaBaselineCommitHash: string | null;

  /**
   * Current HEAD commit hash when this run was executed
   */
  @Column({ type: 'varchar', length: 64, nullable: true })
  currentCommitHash: string | null;

  /**
   * Status of the run
   */
  @Column({ length: 20, default: 'running' })
  status: ReconciliationRunStatus;

  /**
   * Options used for this run
   */
  @Column('jsonb', { default: {} })
  options: ReconciliationRunOptions;

  /**
   * Summary statistics of the run
   */
  @Column('jsonb', { nullable: true })
  summary: ReconciliationSummary | null;

  /**
   * The reconciliation patch containing all operations
   */
  @Column('jsonb', { default: [] })
  patchOps: Record<string, unknown>[];

  /**
   * Optional project association
   */
  @Column({ type: 'uuid', nullable: true })
  projectId: string | null;

  @ManyToOne('Project', { nullable: true })
  @JoinColumn({ name: 'projectId' })
  project: Project | null;

  /**
   * Error message if run failed
   */
  @Column('text', { nullable: true })
  errorMessage: string | null;

  @CreateDateColumn()
  createdAt: Date;

  @Column({ type: 'timestamp', nullable: true })
  completedAt: Date | null;

  /**
   * Atom recommendations generated by this run
   */
  @OneToMany('AtomRecommendation', 'run')
  atomRecommendations: AtomRecommendation[];

  /**
   * Molecule recommendations generated by this run
   */
  @OneToMany('MoleculeRecommendation', 'run')
  moleculeRecommendations: MoleculeRecommendation[];

  /**
   * Test records from this run
   */
  @OneToMany('TestRecord', 'run')
  testRecords: TestRecord[];
}
